- name: Add PostgreSQL repository
  ansible.builtin.command: 'dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm'

- name: Remove PostgreSQL built-in repository
  ansible.builtin.command: 'dnf -qy module disable postgresql'
