#- name: Add official Zabbix repository
#  ansible.builtin.command: 'rpm -Uvh https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm'

- name: Add official Zabbix repository
  ansible.builtin.command: 'rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm'

- name: Clear dnf packet manager cache
  ansible.builtin.command: 'dnf clean all'
