- name: Install policycoreutils-python-utils
  ansible.builtin.dnf:
    name: policycoreutils-python-utils
    state: latest

- name: Install semanage python library
  ansible.builtin.dnf:
    name: libsemanage
    state: latest

- name: Config SELinux to allow httpd_can_network_connect
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Config SeLinux to allow zabbix_can_network
  ansible.posix.seboolean:
    name: zabbix_can_network
    state: yes
    persistent: yes

