- name: Update RedHat Family OS
  ansible.builtin.dnf:
   name: "*"
   state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Update Debian Family OS
  ansible.builtin.apt:
   name: "*"
   state: latest
  when: ansible_facts['os_family'] == "Debian"
