---
- name: "[*] - TDSXX deployment - [*]"

  hosts: TDSXX

  vars_files:
    - vars.yml

#  roles:
#    <-role>

  pre_tasks:
    -name: Ping hosts
     ansible.windows.win_ping:

  tasks:
   - import_tasks: $ANSIBLE_PATH/tasks/general/ws_update.yml

   - import_tasks: $ANSIBLE_PATH/tasks/general/change_hostname.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/disable_ipv6.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/join_domain.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/domainuser_admin.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/disk_partition.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/create_folders.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/def_packages.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/dep_packages.yml

#   - import_tasks: $ANSIBLE_PATH/tasks/general/power_plan.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/aviso_legal.yml

   - import_tasks: $ANSIBLE_PATH/tasks/TDSXX/delete_installfolder.yml
