---
- hosts: WS2K_DEVTEST

  vars_files:
    - vars.yml

#  roles:
#    - <role>

  pre_tasks:
   - name: Ping hosts
     ansible.windows.win_ping:

  tasks:
   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/ws_update.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/change_hostname.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/disk_partition.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/disable_ipv6.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/ws_featandserv.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/ws_services.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/pre_packages.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/disable_firewall.yml

#   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/power_plan.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/enable_rdp.yml

   - import_tasks: $ANSIBLE_PATH/tasks/WS2K_DEVTEST/ms_sql.yml

# find a way to import reboot task in others

#  post-tasks:
#    - disable WinRM
