- name: Install OpenSSH service
  chocolatey.chocolatey.win_chocolatey:
   name: openssh
   package_params: /SSHServerFeature
   state: present 

- name: Configure OpenSSH server
  ansible.builtin.win_regedit:
   path: HKLM:\SOFTWARE\OpenSSH
   name: DefaultShell
   data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
   type: string
   state: present
