---

- name: "[*] - ZABBIX SERVER DEPLOYMENT - [*]"
  hosts: ZABBIX_IaC
  become: yes
  gather_facts: true

  tasks:

  - import_tasks: ~/.ansible/tasks/linux/zabbix/zabbix_srv/config_zabbixservices.yml
